import { createSelector } from '@reduxjs/toolkit';
import { RootState } from '@store/index';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useSelector } from 'react-redux';
import styles from '../styles/Home.module.css';
import { getPostsWithComments } from '@store/selectors';

const Home: NextPage = () => {
  const postsWithComments = useSelector(getPostsWithComments);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>
        Posts with Comments:{' '}
        <pre>{JSON.stringify(postsWithComments, null, 2)}</pre>
      </h1>
    </div>
  );
};

export default Home;
